config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  devise_for :users

  namespace :users do
    resources :posts, only: %i[index edit update destroy]
  end

  resources :users, only: [:show]

  resources :posts, only: %i[index new create show] do
    resources :reactions, only: [:create]
    get 'ogp_image', on: :member
  end

  get 'terms_of_service', to: 'top#terms_of_service'
  get 'privacy_policy', to: 'top#privacy_policy'

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  delegate :path, to: :image, prefix: true
  belongs_to :user
  has_many :reactions, dependent: :destroy

  TEXT_LIMIT = 20

  validates :content,
            presence: true,
            length: { maximum: TEXT_LIMIT }

  generate_public_uid generator: PublicUid::Generators::HexStringSecureRandom.new(20)

  def to_param
    public_uid
  end

  delegate :count, to: :reactions, prefix: true

  def image
    @image ||= Post::Image.new(self)
  end
end

app/models/post/image.rb
# frozen_string_literal: true

class Post::Image
  FRAME_IMAGE_PATH = Rails.root.join('app/assets/images/flame.png')
  FONT_SIZE = 25
  INTERLINE_SPACING = (FONT_SIZE * 0.5).round
  COLOR_CODE = '#333333'
  IMAGE_WIDTH = 640
  IMAGE_HEIGHT = 315
  MAX_ROWS = 5
  COLS = 20
  ROWS = 10

  attr_reader :post

  def initialize(post)
    @post = post
  end

  def create_ogp(image_path)
    FileUtils.mkdir_p(File.dirname(image_path)) unless File.directory?(File.dirname(image_path))
    image.write(image_path)
  end

  private

  def image
    image = MiniMagick::Image.open(FRAME_IMAGE_PATH)
    image.combine_options do |c|
      c.gravity 'Center'
      c.pointsize FONT_SIZE
      c.font font_path
      c.interline_spacing INTERLINE_SPACING
      c.stroke COLOR_CODE
      c.annotate '+0+0', formated_body
    end
  end

  def formated_body
    lines = post.content.lines.map { |line| line.scan(/.{1,#{COLS}}/o) }.flatten
    lines = lines[0, MAX_ROWS - 1].push(OMMIT_MESSAGE) if lines.size > MAX_ROWS
    lines.join('\n')
  end

  def font_path
    Rails.root.join('app/assets/fonts/ZenMaruGothic-Regular.ttf')
  end

  private_constant :FRAME_IMAGE_PATH, :FONT_SIZE, :INTERLINE_SPACING, :COLOR_CODE, :IMAGE_WIDTH, :IMAGE_HEIGHT, :MAX_ROWS, :COLS, :ROWS
end

app/models/reaction.rb
# frozen_string_literal: true

class Reaction < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :timeoutable, :confirmable
  has_many :posts, dependent: :destroy

  validates :name,
            presence: true,
            length: { maximum: 10 }

  generate_public_uid generator: PublicUid::Generators::HexStringSecureRandom.new(20)

  def to_param
    public_uid
  end

  def self.guest
    find_or_create_by!(email: 'guest@guest.mail') do |user|
      user.name = 'ゲストユーザー'
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    root_path
  end

  def after_sign_out_path_for(_resource_or_scope)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < PublicApplicationController
  def index
    @posts = Post.where(id: Post.order(created_at: :desc).limit(100)).order('RANDOM()').limit(10)
  end

  def show
    @post = Post.find_by!(public_uid: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user ? current_user.id : User.guest.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'えらすぎを投稿しました' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def ogp_image
    @post = Post.find_by!(public_uid: params[:id])
    image_path = generate_image_path(@post)
    @post.image.create_ogp(image_path) unless File.exist?(image_path)
    send_file image_path, type: 'image/png', disposition: 'inline'
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :public_uid)
  end

  def current_user?(user)
    user == current_user
  end

  def generate_image_path(post)
    Rails.root.join('tmp', 'ogp_image', "#{post.public_uid}_#{post.updated_at.to_i}.png").to_s
  end
end

app/controllers/public_application_controller.rb
# frozen_string_literal: true

class PublicApplicationController < ApplicationController
  skip_before_action :authenticate_user!
end

app/controllers/reactions_controller.rb
# frozen_string_literal: true

class ReactionsController < PublicApplicationController
  def create
    @post = Post.find(params[:post_id])
    @reaction = @post.reactions.create!
  end
end

app/controllers/top_controller.rb
# frozen_string_literal: true

class TopController < PublicApplicationController
  def terms_of_service; end

  def privacy_policy; end
end

app/controllers/users/posts_controller.rb
# frozen_string_literal: true

class Users::PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy]

  def index
    @posts = current_user.posts.order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.turbo_stream { flash.now[:notice] = 'えらすぎを更新しました' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.turbo_stream { flash.now[:notice] = 'えらすぎを削除しました' }
    end
  end

  private

  def set_post
    @post = current_user.posts.find_by!(public_uid: params[:id])
  end

  def post_params
    params.require(:post).permit(:content)
  end

  def current_user?(user)
    user == current_user
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < PublicApplicationController
  before_action :set_user, only: %i[show]
  before_action :correct_user, only: %i[show]

  def show; end

  private

  def set_user
    @user = User.find_by(public_uid: params[:id])
  end

  def correct_user
    if current_user.nil?
      redirect_to(new_user_session_path)
    elsif !current_user?(@user)
      render file: Rails.public_path.join('404.html'), status: :not_found, layout: false, content_type: 'text/html'
    end
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'えらすぎ'
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def count_characters(post)
    content_length = post.content&.length.to_i
    content_length > Post::TEXT_LIMIT ? "#{content_length - Post::TEXT_LIMIT}文字オーバーです" : "残り#{Post::TEXT_LIMIT - content_length}文字入力できます"
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_flash.html.erb
<div id="flash" data-controller="flash" data-action="clipboard:copy@window->flash#displayMessage" data-flash-text-param="URLをコピーしました" data-flash-target="container">
  <div id="flash-message" data-flash-target="element">
    <% flash.each do |flash_type, message| %>
      <% if flash_type == "notice" %>
        <div data-controller="removal" class="animate-disappear flex justify-center" data-action="animationend->removal#remove">
          <div class="flex justify-center items-center bg-white bg-opacity-80 h-[8svh] px-4 fixed w-screen sm:w-[640px]">
            <div class="p-[2svh] text-[#7FBE17]">
              <%= message %>
            </div>
          </div>
        </div>
      <% elsif flash_type == "alert" %>
        <div class="flex justify-center">
          <div class="flex justify-center items-center bg-white bg-opacity-80 h-[8svh] px-4 fixed w-screen sm:w-[640px]">
            <div class="p-[2svh] error">
              <%= message %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<nav class="select-none">
  <ul class="flex gap-4">
    <li><%= link_to '利用規約', terms_of_service_path %></li>
    <li><%= link_to 'プライバシーポリシー', privacy_policy_path %></li>
  </ul>
  <ul class="flex items-center justify-center">
    <li>© 2024 monyatto</li>
    <li> <%= link_to "https://github.com/monyatto/erasugi", target: "_blank", class: "flex items-center justify-center", style: "width: 30px; height: 30px;" do %>
        <%= image_tag("/github-mark.png", alt: "GitHubへのリンク", style: "width: 20px; height: 20px;") %>
      <% end %></li>
  </ul>
</nav>

app/views/layouts/_header.html.erb
<div class="ms-10">
  <h1><%= link_to 'えらすぎ', posts_path, class: "text-xl font-bold" %></h1>
</div>
<div class="me-10 flex justify-center items-center gap-4">
  <div>
    <%= link_to new_post_path do %>
      <svg class="w-7 h-7" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="m10.8 17.8-6.4 2.1 2.1-6.4m4.3 4.3L19 9a3 3 0 0 0-4-4l-8.4 8.6m4.3 4.3-4.3-4.3m2.1 2.1L15 9.1m-2.1-2 4.2 4.2"/>
      </svg>
    <% end %>
  </div>
  <nav data-controller="hamburger">
    <svg tabindex="0" xmlns="http://www.w3.org/2000/svg" fill="#303030" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="hamburger w-7 h-7 outline-none cursor-pointer" data-hamburger-target="svg" data-action="click->hamburger#openAndClose">
      <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5M12 17.25h8.25"/>
    </svg>
    <div class="invisible absolute top-16 right-10" data-hamburger-target="menuItems">
      <ul tabindex="0" class="shadow bg-white rounded-lg p-4">
        <% if user_signed_in? %>
          <li class="hover:bg-neutral-100"><%= link_to 'みんなの投稿一覧', posts_path, class: "px-4 py-2 block" %></li>
          <li class="hover:bg-neutral-100"><%= link_to "#{current_user.name}の投稿一覧", users_posts_path, class: "px-4 py-2 block" %></li>
          <li class="hover:bg-neutral-100"><%= link_to '登録情報', user_path(current_user), class: "px-4 py-2 block" %></li>
          <li class="hover:bg-neutral-100"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "px-4 py-2 block" %></li>
        <% else %>
          <li class="hover:bg-neutral-100"><%= link_to "新規登録", new_user_registration_path, class: "px-4 py-2 block" %></li>
          <li class="hover:bg-neutral-100"><%= link_to "ログイン", new_user_session_path, class: "px-4 py-2 block" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_unlogin.html.erb
<% if current_user.nil? %>
  <div class="flex flex-col justify-center items-center h-[8svh] fixed z-10 bottom-[10svh] bg-neutral-100 bg-opacity-80 sm:w-[640px] w-full text-sm">
    <p>会員登録すると過去の投稿が見やすくなります</p>
    <p>
      <%= link_to "新規登録", new_user_registration_path, class: "underline" %>
      または
      <%= link_to "ログイン", new_user_session_path, class: "underline" %>
    </p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# article: http://ogp.me/ns/article#">
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta name="description" content="えらすぎは匿名で気軽に褒めたり褒められたりできる無料のWebサービスです。">
  <meta name="keyword" content="えらすぎ, 褒められる, 褒める, えらい, ポジティブ, フィードバック, コミュニティ, モチベーション, やる気, Ruby, Rails, Rails 7, Hotwire, Swiper, Konva">
  <meta property="og:type" content="website"/>
  <meta property="og:url" content="https://erasugi.onrender.com/"/>
  <meta property="og:image" content="<%= image_url('ogp.png') %>"/>
  <meta property="og:site_name" content="えらすぎ"/>
  <meta property="og:description" content="えらすぎは匿名で気軽に褒めたり褒められたりできる無料のWebサービスです。"/>
  <meta name="twitter:card" content="summary_large_image"/>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font" %>
  <%= stylesheet_link_tag "application" %>
  <%= stylesheet_link_tag "swiper" %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css">
  <link rel="icon" href="/favicon.ico" sizes="any">
  <link rel="icon" href="/icon.svg" type="image/svg+xml">
  <link rel="apple-touch-icon" href="/apple-touch-icon.png">
  <%= javascript_importmap_tags %>
  <%= yield :extra_head %>
</head>
<body>
<div class="h-[100svh] flex flex-col items-center justify-center">
  <header class="h-[10svh] flex items-center justify-between fixed top-0 z-50 bg-white bg-opacity-80 w-screen sm:w-[640px]">
    <%= render "layouts/header" %>
  </header>
  <div id="container" class="absolute"></div>
  <main class="w-full sm:w-[640px]">
    <%= render "layouts/flash" %>
    <div class="h-[80svh]">
      <%= yield %>
    </div>
  </main>
  <footer class="h-[10svh] flex items-center justify-center fixed bottom-0 z-50 bg-white bg-opacity-80 w-screen sm:w-[640px]">
    <%= render "layouts/footer" %>
  </footer>
</div>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <%= stylesheet_link_tag "tailwind", "inter-font" %>
  <%= stylesheet_link_tag "application" %>
  <%= yield :extra_head %>
</head>
<body>
<main class="h-svh flex flex-col items-center justify-center mx-10 gap-8">
  <%= yield %>
</main>
</body>
</html>

app/views/posts/_error_messages.html.erb
<% if form.object.errors.any? %>
  <div class="error">
    <ul>
      <% form.object.errors.full_messages.each do |message| %>
        <li class="text-center"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/posts/_new.html.erb
<div class="absolute right-20 bottom-20">
<%= render "layouts/modal", title: "登録" do %>
  <%= render "posts/form", post: Post.new, class: "textarea textarea-bordered" %>
<% end %>
</div>

app/views/posts/_share.html.erb
<div class="flex justify-center gap-5">
  <%= link_to "https://twitter.com/intent/tweet?text=#{ERB::Util.url_encode(post.content)}%20%23えらすぎ%0A#{post_url(post)}", target: "_blank", class: "bg-black rounded-md flex items-center justify-center sm:w-8 sm:h-8 w-10 h-10", id: "x-share" do %>
    <%= image_tag("/x.png", alt: "Xへのシェア", class: "sm:w-4 sm:h-4 w-5 h-5") %>
  <% end %>
  <%= link_to "https://social-plugins.line.me/lineit/share?url=#{post_url(post)}", target: "_blank", class: "flex items-center justify-center", id: "line-share" do %>
    <%= image_tag("/line.png", alt: "Lineへのシェア", class: "sm:w-8 sm:h-8 w-10 h-10") %>
  <% end %>
  <div data-controller="clipboard" class="flex items-center justify-center">
    <%= link_to "", target: "_blank", class: "bg-stone-400 rounded-md flex items-center justify-center sm:w-8 sm:h-8 w-10 h-10", id: "url-copy", data: { action: "clipboard#copy", "clipboard-target": "url" }, value: post_url(post) do %>
      <%= image_tag("/link.png", alt: "URLをコピー", class: "sm:w-5 sm:h-5 w-6 h-6") %>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "post_#{@post.public_uid}", class: "flex justify-center" do %>
  <% content_for :extra_head do %>
    <meta name="description" content="投稿編集画面です。">
  <% end %>
  <div data-controller="count" data-count-text-limit-value="<%= Post::TEXT_LIMIT %>">
    <%= form_with(model: @post) do |form| %>
      <%= render "posts/error_messages", form: form %>
      <div class="flex flex-col justify-center items-center pb-4">
        <%= form.text_area :content, class: "block rounded-md h-[10svh] w-[36svh]", data: { count_target: "input", action: "keyup->count#updateDisplay" } %>
        <p class="text-sm mt-2" data-count-target="display"><%= count_characters(@post) %></p>
      </div>
      <div class="flex justify-center gap-4 text-sm">
        <%= form.submit "更新する", class: "py-2 bg-neutral-100 w-[16svh] rounded-md shadow-md cursor-pointer hover:bg-opacity-50" %>
        <%= link_to 'キャンセル', '', class: "text-center py-2 bg-neutral-100 w-[16svh] rounded-md shadow-md cursor-pointer hover:bg-opacity-50" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/index.html.erb
<% content_for(:title, '投稿一覧') %>
<%= render "layouts/unlogin" %>
<div class="swiper" id="swiper_id" data-controller="scroll" data-scroll-posts-ids-value="<%= @posts.map(&:id) %>">
  <div class="swiper-wrapper">
    <% @posts.each do |post| %>
      <div data-controller="reaction" data-reaction-post-id-value="<%= post.id %>" data-reaction-first-post-id-value="<%= @posts.first.id %>" data-reaction-associated-reactions-value="<%= post.reactions_count %>" data-reaction-target="load" data-action="scroll:setActivePostId@window->reaction#postIdChanged" class="swiper-slide flex flex-col justify-center select-none">
        <div class="flex justify-center mb-[20svh] px-5 sm:px-0">
          <p class="text-4xl break-words text-center leading-relaxed font-black bg-white bg-opacity-50 test-post-content"><%= post.content %></p>
        </div>
        <div class="flex flex-wrap justify-center gap-2 px-10 sm:px-0">
          <button data-action="reaction#onButtonClick" data-reaction-target="button" class="absolute bottom-32 h-20 hover:h-[79px] active:h-[69px] w-32 bg-stone-200 border-l-10 border-l-stone-100 border-r-10 border-r-stone-300 border-b-15 hover:border-b-14 active:border-b-4 border-b-stone-400 rounded-md text-neutral-600 opacity-65 hover:opacity-65 active:opacity-65 transition-all duration-200 ease-out test-display-button-<%= post.id %>">えらい</button>
        </div>
      </div>
    <% end %>
  </div>
</div>
<div class="swiper-button-next" id="swiper-button-next"></div>
<div class="swiper-button-prev" id="swiper-button-prev"></div>
<div class="swiper-pagination"></div>

app/views/posts/new.html.erb
<% content_for(:title, '新規投稿') %>
<% content_for :extra_head do %>
  <meta name="description" content="新規投稿画面です。">
<% end %>
<%= render "layouts/unlogin" %>
<div data-controller="count" data-count-text-limit-value="<%= Post::TEXT_LIMIT %>" class="h-[80svh] flex flex-col justify-center items-center">
  <%= form_with(model: @post) do |form| %>
    <div class="flex flex-col justify-center items-center space-y-4 w-screen h-[80svh]">
        <%= render "posts/error_messages", form: form %>
      <div>
        <%= form.label :content, 'あたらしいえらすぎ', class: "text-xl" %>
      </div>
      <div class="flex flex-col justify-center items-center ">
        <%= form.text_area :content, placeholder: '午前中に起きた！', class: "block rounded-md h-[25svh] w-[40svh] placeholder-stone-400", data: { count_target: "input", action: "keyup->count#updateDisplay" } %>
        <p class="text-sm mt-2" data-count-target="display"><%= count_characters(@post) %></p>
      </div>
      <div>
        <%= form.submit "投稿する", class: "py-2 bg-neutral-100 w-[40svh] rounded-md shadow-md cursor-pointer hover:bg-opacity-50" %>
      </div>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<% content_for(:title, '投稿詳細') %>
<% content_for :extra_head do %>
  <meta name="description" content="投稿詳細画面です。">
  <meta property="og:type" content="article"/>
  <meta property="og:url" content="#{post_url(@post)"/>
  <meta property="og:image" content="<%= ogp_image_post_url(@post) %>"/>
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="えらすぎ">
  <meta name="twitter:description" content="<%= @post.content %>">
  <meta name="twitter:image" content="<%= ogp_image_post_url(@post) %>">
<% end %>
<div id="container" class="absolute"></div>
<div data-controller="reaction" data-reaction-post-id-value="<%= @post.id %>" data-reaction-first-post-id-value="<%= @post.id %>" data-reaction-associated-reactions-value="<%= @post.reactions_count %>" data-reaction-target="load" class="h-[80svh] flex flex-col justify-center select-none">
  <div class="z-10">
    <div class="flex justify-center items-center px-5 sm:px-0 mb-[4svh]">
      <p class="text-3xl break-words text-center leading-relaxed font-black bg-white bg-opacity-50"><%= @post.content %></p>
    </div>
    <div class="z-30 flex justify-center mb-[16svh]">
      <%= render "share", post: @post %>
    </div>
    <div class="flex justify-center px-10 sm:px-0">
      <button data-action="reaction#onButtonClick" data-reaction-target="button" class="absolute bottom-[200px] h-20 hover:h-[79px] active:h-[69px] w-32 bg-stone-200 border-l-10 border-l-stone-100 border-r-10 border-r-stone-300 border-b-15 hover:border-b-14 active:border-b-4 border-b-stone-400 rounded-md text-neutral-600 opacity-65 hover:opacity-65 active:opacity-65 transition-all duration-200 ease-out test-display-button-<%= @post.id %>">えらい</button>
    </div>
  </div>
</div>

app/views/top/index.html.erb
<div class="text-3xl font-bold underline">test</div>
<div class="bg-black h-7 w-7"></div>

app/views/users/posts/_post.html.erb
<%= turbo_frame_tag "post_#{post.public_uid}", class: "flex flex-col mr-5 ml-5 mt-2 mb-2 p-3 pb-4 border border-stone-900 rounded-lg" do %>
  <%= link_to post_path(post.public_uid), target: "_top", class: "flex flex-col" do %>
    <div class="flex items-center justify-between">
      <div class="ms-0">
        <%= post.created_at.to_date.strftime("%Y年%m月%d日") %>
      </div>
      <div class="me-0 flex justify-center gap-2">
        <div>
          <%= button_to edit_users_post_path(id: post.public_uid), method: :get, id: "edit-button" do %>
            <svg class="w-7 h-7 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
              <path stroke="#303030" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="m14.3 4.8 2.9 2.9M7 7H4a1 1 0 0 0-1 1v10c0 .6.4 1 1 1h11c.6 0 1-.4 1-1v-4.5m2.4-10a2 2 0 0 1 0 3l-6.8 6.8L8 14l.7-3.6 6.9-6.8a2 2 0 0 1 2.8 0Z"/>
            </svg>
          <% end %>
        </div>
        <div>
          <%= button_to users_post_path(post), method: :delete, id: "delete-button", data: { turbo_confirm: "本当に削除しますか？" } do %>
            <svg class="w-7 h-7 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 25 25">
              <path stroke="#303030" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M5 7h14m-9 3v8m4-8v8M10 3h4a1 1 0 0 1 1 1v3H9V4a1 1 0 0 1 1-1ZM6 7h12v13a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7Z"/>
            </svg>
          <% end %>
        </div>
      </div>
    </div>
    <div class="text-lg font-bold">
      <%= post.content %>
    </div>
  <% end %>
<% end %>

app/views/users/posts/destroy.turbo_stream.erb
<%= turbo_stream.remove "post_#{@post.public_uid}" %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>